// packages/react-library/demo/components/AuthorCard.tsx
'use client';

import { Avatar, Group, Paper, Stack, Text } from '@mantine/core';
import { PidComponent } from '../../lib';

interface Author {
  orcid: string;
  name: string;
  role?: string;
  institution?: string;
}

interface AuthorCardProps {
  author: Author;
  darkMode?: boolean;
}

export function AuthorCard({ author, darkMode = false }: AuthorCardProps) {
  const initials = author.name.split(' ').map(n => n[0]).join('');

  return (
    <Paper className={darkMode ? 'bg-gray-800' : 'bg-white'} shadow="sm" padding="lg" radius="md" withBorder
           style={{ overflow: 'hidden' }}>
      <Group gap="md" align="flex-start">
        <Avatar size={48} radius="xl" color="indigo" className={darkMode ? 'bg-indigo-700' : ''}>
          {initials}
        </Avatar>
        <Stack gap={4} style={{ flex: 1, minWidth: 0 }}>
          <Text fw={600} size="sm" className={darkMode ? 'text-white' : 'text-gray-900'}
                style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{author.name}</Text>
          <Text size="xs" c={darkMode ? 'gray.5' : 'dimmed'}>{author.role}</Text>
          {author.institution && (
            <Text size="xs" c={darkMode ? 'gray.5' : 'dimmed'} style={{
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap',
            }}>{author.institution}</Text>
          )}
          <div style={{ marginTop: 8, minHeight: 24, maxHeight: 80, overflow: 'hidden' }}>
            <PidComponent value={author.orcid} emphasizeComponent={false} darkMode={darkMode ? 'dark' : 'light'}
                          width="100%" />
          </div>
        </Stack>
      </Group>
    </Paper>
  );
}

interface AuthorGridProps {
  authors: Author[];
  darkMode?: boolean;
}

export function AuthorGrid({ authors, darkMode = false }: AuthorGridProps) {
  return (
    <div style={{ marginBottom: 32 }}>
      <Text fw={600} size="md" mb="md" className={darkMode ? 'text-white' : 'text-gray-900'}
            style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        Lorem ipsum dolor sit amet
      </Text>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}>
        {authors.map((author) => (
          <AuthorCard key={author.orcid} author={author} darkMode={darkMode} />
        ))}
      </div>
    </div>
  );
}

// packages/angular-library/src/app/components/author-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

export interface Author {
  orcid: string;
  name: string;
  institution?: string;
}

@Component({
  selector: 'app-author-card',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    PidComponent,
  ],
  template: `
    <mat-card [class]="darkMode ? 'bg-gray-800' : 'bg-white'" class="author-card">
      <div class="author-content">
        <div class="avatar-placeholder">
          {{ getInitials(author.name) }}
        </div>
        <div class="author-info">
          <h3 [class]="darkMode ? 'text-white' : 'text-gray-900'" class="author-name">{{ author.name }}</h3>
          @if (author.institution) {
            <p [class]="darkMode ? 'text-gray-400' : 'text-gray-500'" class="author-institution">{{ author.institution }}</p>
          }
          <div style="min-height: 24px; max-height: 80px; overflow: hidden;">
            <pid-component [value]="author.orcid" [emphasizeComponent]="false" [darkMode]="darkMode ? 'dark' : 'light'"
                           width="100%" />
          </div>
        </div>
      </div>
    </mat-card>
  `,
  styles: [`
    .author-card {
      padding: 20px;
      overflow: hidden;
    }

    .author-content {
      display: flex;
      gap: 16px;
      align-items: flex-start;
    }

    .avatar-placeholder {
      width: 48px;
      height: 48px;
      border-radius: 50%;
      background: #e8eaf6;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 16px;
      font-weight: 600;
      color: #3f51b5;
      flex-shrink: 0;
    }

    .author-info {
      flex: 1;
      min-width: 0;
    }

    .author-name {
      font-size: 16px;
      font-weight: 600;
      margin: 0 0 4px 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .author-role {
      font-size: 13px;
      color: #9e9e9e;
      margin: 0 0 4px 0;
    }

    .author-institution {
      font-size: 12px;
      margin: 0 0 12px 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
  `],
})
export class AuthorCardComponent {
  @Input() author!: Author;
  @Input() darkMode = false;

  getInitials(name: string): string {
    return name.split(' ').map(n => n[0]).join('');
  }
}

@Component({
  selector: 'app-author-grid',
  standalone: true,
  imports: [CommonModule, AuthorCardComponent],
  template: `
    <div class="author-grid">
      <h2 [class]="darkMode ? 'text-white' : 'text-gray-900'" class="grid-title">Lorem ipsum dolor sit amet</h2>
      <div class="grid">
        @for (author of authors; track author.orcid) {
          <app-author-card [author]="author" [darkMode]="darkMode" />
        }
      </div>
    </div>
  `,
  styles: [`
    .author-grid {
      margin-bottom: 32px;
    }

    .grid-title {
      font-size: 18px;
      font-weight: 600;
      margin-bottom: 16px;
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 16px;
    }
  `],
})
export class AuthorGridComponent {
  @Input() authors: Author[] = [];
  @Input() darkMode = false;
}
