// packages/vue-library/demo/components/DoiCard.vue
<script lang="ts" setup>
import { PidComponent } from '../../lib';

defineProps<{
  value: string;
  license?: string;
  darkMode?: boolean;
}>();
</script>

<template>
  <v-card :color="darkMode ? 'grey-darken-3' : 'white'" class="fill-height" elevation="1">
    <v-card-text>
      <div class="text-caption text-uppercase font-weight-bold mb-3"
           :class="darkMode ? 'text-grey-lighten-1' : 'text-grey-darken-2'">
        Digital Object Identifier
      </div>
      <div style="min-height: 120px; max-height: 300px; overflow: hidden;">
        <pid-component :value="value" :dark-mode="darkMode ? 'dark' : 'light'" style="display: block;" width="100%" />
      </div>
      <v-divider v-if="license" class="my-4"></v-divider>
      <template v-if="license">
        <div class="text-caption text-uppercase font-weight-bold mb-3"
             :class="darkMode ? 'text-grey-lighten-1' : 'text-grey-darken-2'">
          License
        </div>
        <div style="min-height: 80px; max-height: 200px; overflow: hidden;">
          <pid-component :value="license" :dark-mode="darkMode ? 'dark' : 'light'" style="display: block;"
                         width="100%" />
        </div>
      </template>
    </v-card-text>
  </v-card>
</template>

// packages/angular-library/src/app/components/doi-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatDividerModule } from '@angular/material/divider';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-doi-card',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatDividerModule,
    PidComponent,
  ],
  template: `
    <mat-card [class]="darkMode ? 'bg-gray-800' : 'bg-white'" class="doi-card">
      <mat-card-content>
        <h3 [class]="darkMode ? 'text-gray-300' : 'text-gray-500'" class="label">Digital Object Identifier</h3>
        <div style="min-height: 120px; max-height: 300px; overflow: hidden;">
          <pid-component [value]="value" [openByDefault]="true" [darkMode]="darkMode ? 'dark' : 'light'" width="100%" />
        </div>
        @if (license) {
          <mat-divider></mat-divider>
          <h3 [class]="darkMode ? 'text-gray-300' : 'text-gray-500'" class="label" style="margin-top: 16px">License</h3>
          <div style="min-height: 80px; max-height: 200px; overflow: hidden;">
            <pid-component [value]="license" [darkMode]="darkMode ? 'dark' : 'light'" width="100%" />
          </div>
        }
      </mat-card-content>
    </mat-card>
  `,
  styles: [`
    .doi-card {
      padding: 24px;
      height: 100%;
      overflow: hidden;
    }

    .label {
      font-size: 12px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-bottom: 12px;
    }
  `],
})
export class DoiCardComponent {
  @Input() value = '';
  @Input() license?: string;
  @Input() darkMode = false;
}
