// packages/react-library/demo/components/Footer.tsx
'use client';

import { Button, Container, Group, Text } from '@mantine/core';
import { IconDatabase } from '@tabler/icons-react';
import { PidComponent } from '../../lib';

interface FooterProps {
  darkMode?: boolean;
}

export function Footer({ darkMode = false }: FooterProps) {
  return (
    <div className={darkMode ? 'bg-gray-800' : 'bg-white'} style={{
      borderTop: darkMode ? '1px solid #4b5563' : '1px solid #e0e0e0',
      marginTop: 48,
    }}>
      <Container size="xl">
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          padding: '24px 0',
          gap: '16px',
        }}>
          <Group gap="sm">
            <Button
              variant="filled"
              color="indigo"
              size="xs"
              leftSection={<IconDatabase size={14} />}
              radius="md"
              className={darkMode ? 'text-white' : ''}
            >
              Lorem ipsum
            </Button>
          </Group>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Text size="sm" c={darkMode ? 'gray.4' : 'dimmed'} style={{ whiteSpace: 'nowrap' }}>Powered by</Text>
            <div style={{ flex: 1, minWidth: 0 }}>
              <PidComponent value="https://ror.org/04t3en479" emphasizeComponent={false} hideSubcomponents={true}
                            darkMode={darkMode ? 'dark' : 'light'} />
            </div>
          </div>
        </div>
      </Container>
    </div>
  );
}

// packages/angular-library/src/app/components/footer.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    PidComponent,
  ],
  template: `
    <footer [class]="darkMode ? 'bg-gray-900 text-white' : 'bg-gray-50 text-gray-900'" style="display: flex; justify-content: space-between; align-items: center; padding: 16px 24px; margin-top: 48px;">
      <div style="display: flex; align-items: center; gap: 12px;">
        <button mat-mini-fab [color]="darkMode ? 'accent' : 'primary'" disabled style="width: 40px; height: 40px;">
          <mat-icon [class.text-white]="darkMode" [class.text-gray-900]="!darkMode">storage</mat-icon>
        </button>
        <span style="font-size: 14px; font-weight: 600;">Lorem ipsum</span>
      </div>
      <div style="display: flex; align-items: center; gap: 8px;">
        <span [class]="darkMode ? 'text-gray-400' : 'text-gray-500'" style="font-size: 14px; white-space: nowrap;">Powered by</span>
        <div style="flex: 1; min-width: 0;">
          <pid-component value="https://ror.org/04t3en479" [emphasizeComponent]="false" [hideSubcomponents]="true"
                         [darkMode]="darkMode ? 'dark' : 'light'" />
        </div>
      </div>
    </footer>
  `,
  styles: [`:host {
    display: block;
  }`],
})
export class FooterComponent {
  @Input() darkMode = false;
}
