// packages/nextjs-app/app/components/Footer.tsx
import { Database } from 'lucide-react';
import { PidComponent } from '@kit-data-manager/react-pid-component';

interface FooterProps {
  darkMode?: boolean;
}

export function Footer({ darkMode = false }: FooterProps) {
  return (
    <footer className="border-t mt-12">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{
              display: 'flex',
              height: '32px',
              width: '32px',
              alignItems: 'center',
              justifyContent: 'center',
              borderRadius: '8px',
              backgroundColor: 'hsl(var(--primary))',
            }}>
              <Database className="h-4 w-4 text-primary-foreground" />
            </div>
            <span style={{ fontSize: '14px', fontWeight: 600, color: 'hsl(var(--foreground))' }}>Lorem ipsum</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{
              fontSize: '14px',
              color: 'hsl(var(--muted-foreground))',
              whiteSpace: 'nowrap',
            }}>Powered by</span>
            <div style={{ flex: 1, minWidth: 0 }}>
              <PidComponent value="https://ror.org/04t3en479" emphasizeComponent={false} hideSubcomponents={true}
                            darkMode={darkMode ? 'dark' : 'light'} width="100%" />
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// packages/angular-library/src/app/components/footer.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    PidComponent,
  ],
  template: `
    <footer [class]="darkMode ? 'bg-gray-900 text-white' : 'bg-gray-50 text-gray-900'" style="display: flex; justify-content: space-between; align-items: center; padding: 16px 24px; margin-top: 48px;">
      <div style="display: flex; align-items: center; gap: 12px;">
        <button mat-mini-fab [color]="darkMode ? 'accent' : 'primary'" disabled style="width: 40px; height: 40px;">
          <mat-icon [class.text-white]="darkMode" [class.text-gray-900]="!darkMode">storage</mat-icon>
        </button>
        <span style="font-size: 14px; font-weight: 600;">Lorem ipsum</span>
      </div>
      <div style="display: flex; align-items: center; gap: 8px;">
        <span [class]="darkMode ? 'text-gray-400' : 'text-gray-500'" style="font-size: 14px; white-space: nowrap;">Powered by</span>
        <div style="flex: 1; min-width: 0;">
          <pid-component value="https://ror.org/04t3en479" [emphasizeComponent]="false" [hideSubcomponents]="true"
                         [darkMode]="darkMode ? 'dark' : 'light'" />
        </div>
      </div>
    </footer>
  `,
  styles: [`:host {
    display: block;
  }`],
})
export class FooterComponent {
  @Input() darkMode = false;
}
