// packages/nextjs-app/app/demo/components/Footer.tsx
import { Database } from 'lucide-react';
import { PidComponent } from '@kit-data-manager/react-pid-component';

export function Footer() {
  return (
    <footer className="border-t border-slate-200 bg-white mt-12">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{
              display: 'flex',
              height: '32px',
              width: '32px',
              alignItems: 'center',
              justifyContent: 'center',
              borderRadius: '8px',
              backgroundColor: '#4f46e5',
            }}>
              <Database className="h-4 w-4 text-white" />
            </div>
            <span style={{ fontSize: '14px', fontWeight: 600, color: '#0f172a' }}>ResearchDemo</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '14px', color: '#64748b', whiteSpace: 'nowrap' }}>Powered by</span>
            <div style={{ flex: 1, minWidth: 0 }}>
              <PidComponent value="https://ror.org/04t3en479" emphasizeComponent={false} hideSubcomponents={true} />
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// packages/angular-library/src/app/components/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    PidComponent,
  ],
  template: `
    <footer style="display: flex; justify-content: space-between; align-items: center; padding: 16px 24px; background: #212121; margin-top: 48px;">
      <div style="display: flex; align-items: center; gap: 12px;">
        <button mat-mini-fab color="accent" disabled style="width: 40px; height: 40px;">
          <mat-icon>storage</mat-icon>
        </button>
        <span style="font-size: 14px; font-weight: 600; color: white;">ResearchDemo</span>
      </div>
      <div style="display: flex; align-items: center; gap: 8px;">
        <span style="font-size: 14px; color: #9e9e9e; white-space: nowrap;">Powered by</span>
        <div style="flex: 1; min-width: 0;">
          <pid-component value="https://ror.org/04t3en479" [emphasizeComponent]="false" [hideSubcomponents]="true" />
        </div>
      </div>
    </footer>
  `,
  styles: [`:host {
    display: block;
  }`],
})
export class FooterComponent {
}
