// packages/nextjs-app/app/components/HeroCard.tsx
import { Download, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { PidComponent } from '@kit-data-manager/react-pid-component';
import { cn } from '../lib/utils';

interface HeroCardProps {
  title: string;
  description: string;
  doi?: string;
  actions?: React.ReactNode;
  className?: string;
  darkMode?: boolean;
}

/**
 * Primary hero card component for the demo portal.
 * Uses shadcn/ui card, button, and badge components.
 */
export function HeroCard({ title, description, actions, className, darkMode = false }: HeroCardProps) {
  return (
    <Card className={cn(darkMode ? 'bg-slate-800 border-slate-700' : '', className)}>
      <CardHeader>
        <div className="flex gap-2">
          <Badge variant="default" className={darkMode ? 'bg-blue-900 text-blue-200' : 'bg-blue-100 text-blue-700'}>
            DOI
          </Badge>
          <Badge variant="secondary"
                 className={darkMode ? 'bg-emerald-900 text-emerald-200' : 'bg-emerald-100 text-emerald-700'}>
            Research Data
          </Badge>
        </div>
        <CardTitle className={cn('mt-4 text-2xl font-bold', darkMode ? 'text-white' : 'text-slate-900')}>
          {title}
        </CardTitle>
        <CardDescription className={cn(darkMode ? 'text-slate-400' : 'text-slate-600')}>
          {description}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex gap-3">
          {actions || (
            <>
              <Button>
                <Download className="h-4 w-4" />
                Download Dataset
              </Button>
              <Button variant="outline" className={darkMode ? 'border-slate-600 bg-slate-700 text-slate-200' : ''}>
                <ExternalLink className="h-4 w-4" />
                View Source
              </Button>
            </>
          )}
        </div>
      </CardContent>
    </Card>
  );
}

// packages/angular-library/src/app/components/hero-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-hero-card',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatChipsModule,
    MatButtonModule,
    MatIconModule,
    MatDividerModule,
    PidComponent,
  ],
  template: `
    <mat-card [class]="darkMode ? 'bg-gray-800' : 'bg-white'" class="hero-card">
      <mat-card-header>
        <mat-chip-set>
          <mat-chip color="primary" highlighted>DOI</mat-chip>
          <mat-chip color="accent" highlighted>Research Data</mat-chip>
        </mat-chip-set>
      </mat-card-header>
      <mat-card-content>
        <h1 [class]="darkMode ? 'text-white' : 'text-gray-900'" class="hero-title">{{ title }}</h1>
        <p [class]="darkMode ? 'text-gray-300' : 'text-gray-600'" class="hero-description">{{ description }}</p>
      </mat-card-content>
      <mat-card-actions>
        <button mat-flat-button color="primary">
          <mat-icon>download</mat-icon>
          Download Dataset
        </button>
        <button mat-stroked-button [color]="darkMode ? 'accent' : 'primary'">
          <mat-icon>open_in_new</mat-icon>
          View Source
        </button>
      </mat-card-actions>
    </mat-card>
  `,
  styles: [`
    .hero-card {
      padding: 24px;
    }

    .hero-title {
      font-size: 24px;
      font-weight: 700;
      margin: 16px 0;
      line-height: 1.3;
    }

    .hero-description {
      font-size: 14px;
      line-height: 1.6;
      margin-bottom: 24px;
    }

    mat-card-actions {
      display: flex;
      gap: 12px;
    }
  `],
})
export class HeroCardComponent {
  @Input() title = '';
  @Input() description = '';
  @Input() darkMode = false;
}
