// packages/angular-library/src/app/components/license-dialog.component.ts
import { Component, Inject, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-license-dialog',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatDialogModule,
    MatIconModule,
    PidComponent,
  ],
  template: `
    <mat-card class="license-card" [class]="darkMode ? 'bg-gray-800' : 'bg-white'">
      <h2 class="card-title" [class]="darkMode ? 'text-white' : 'text-gray-900'">
        <mat-icon [class]="darkMode ? 'text-white' : ''">scale</mat-icon>
        License Information
      </h2>
      <button mat-flat-button color="primary" (click)="openDialog()">
        <mat-icon>scale</mat-icon>
        View License Details
      </button>
    </mat-card>
  `,
  styles: [`
    .license-card {
      padding: 24px;
    }

    .card-title {
      font-size: 18px;
      font-weight: 600;
      margin: 0 0 16px 0;
      display: flex;
      align-items: center;
      gap: 8px;
    }
  `],
})
export class LicenseDialogComponent {
  @Input() darkMode = false;

  constructor(private dialog: MatDialog) {
  }

  openDialog() {
    const dialogRef = this.dialog.open(LicenseDialogContentComponent, {
      width: '600px',
      data: { darkMode: this.darkMode },
    });
  }
}

@Component({
  selector: 'app-license-dialog-content',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, PidComponent],
  template: `
    <h2 mat-dialog-title [class]="data.darkMode ? 'text-white' : ''">Apache License 2.0</h2>
    <mat-dialog-content>
      <p [class]="data.darkMode ? 'text-gray-300' : 'text-gray-700'" style="line-height: 1.8; margin-bottom: 16px;">
        This dataset is published under the Apache 2.0 license, allowing free reuse with appropriate attribution.
      </p>
      <div style="min-height: 150px; max-height: 400px; overflow: hidden;">
        <pid-component value="https://spdx.org/licenses/Apache-2.0" [darkMode]="data.darkMode ? 'dark' : 'light'" width="100%" />
      </div>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button (click)="close()" [class]="data.darkMode ? 'text-white' : ''">Close</button>
    </mat-dialog-actions>
  `,
})
export class LicenseDialogContentComponent {
  constructor(
    public dialogRef: MatDialogRef<LicenseDialogContentComponent>,
    @Inject(MAT_DIALOG_DATA) public data: { darkMode: boolean },
  ) {
  }

  close() {
    this.dialogRef.close();
  }
}

// packages/react-library/demo/components/LicenseDialog.tsx
'use client';

import { Button, Group, Modal, Paper, Text } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { IconScale } from '@tabler/icons-react';
import { PidComponent } from '../../lib';

interface LicenseDialogProps {
  darkMode?: boolean;
}

export function LicenseDialog({ darkMode = false }: LicenseDialogProps) {
  const [opened, { open, close }] = useDisclosure(false);

  return (
    <>
      <Paper shadow="sm" padding="xl" radius="md" withBorder
             className={darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}>
        <Text fw={600} size="md" mb="md" style={{ display: 'flex', alignItems: 'center', gap: 8 }}
              className={darkMode ? 'text-white' : 'text-gray-900'}>
          <IconScale size={20} />
          License Information
        </Text>
        <Button onClick={open} color="indigo" leftSection={<IconScale size={16} />}>
          View License Details
        </Button>
      </Paper>

      <Modal
        opened={opened}
        onClose={close}
        title="Apache License 2.0"
        centered
        size="md"
        classNames={{
          content: darkMode ? 'bg-gray-800' : 'bg-white',
          header: darkMode ? 'bg-gray-800' : 'bg-white',
          body: darkMode ? 'bg-gray-800' : 'bg-white',
        }}
      >
        <Text size="sm" c="dimmed" mb="md" className={darkMode ? 'text-gray-300' : ''}>
          This dataset is published under the Apache 2.0 license, allowing free reuse
          with appropriate attribution.
        </Text>
        <div style={{ minHeight: 150, maxHeight: 400, overflow: 'hidden' }}>
          <PidComponent value="https://spdx.org/licenses/Apache-2.0" darkMode={darkMode ? 'dark' : 'light'}
                        width="100%" />
        </div>
        <Group justify="flex-end" mt="xl">
          <Button variant="outline" color="gray" onClick={close}>
            Close
          </Button>
        </Group>
      </Modal>
    </>
  );
}
