// packages/nextjs-app/app/components/AuthorGrid.tsx
import { AuthorCard } from './AuthorCard';
import type { Author } from './AuthorCard';

interface AuthorGridProps {
  authors: Author[];
  className?: string;
}

export function AuthorGrid({ authors, className }: AuthorGridProps) {
  return (
    <div className={className}>
      <h2 className="text-lg font-semibold flex items-center gap-2 mb-4 text-foreground">
        Lorem ipsum dolor sit amet
      </h2>
      <div className="grid grid-cols-3 gap-4">
        {authors.map((author) => (
          <AuthorCard key={author.orcid} author={author} />
        ))}
      </div>
    </div>
  );
}

// packages/vue-library/demo/components/AuthorGrid.vue
<script lang="ts" setup>
import type { Author } from './AuthorCard.vue';
import AuthorCardComponent from './AuthorCard.vue';

defineProps<{
  authors: Author[];
}>();
</script>

<template>
  <div class="mb-8">
    <h2 class="text-h6 font-weight-bold mb-4 d-flex align-center">
      <v-icon class="mr-2" color="grey-darken-2">mdi-account-group</v-icon>
      Lorem ipsum dolor sit amet
    </h2>
    <v-row>
      <v-col v-for="author in authors" :key="author.orcid" cols="4">
        <AuthorCardComponent :author="author" />
      </v-col>
    </v-row>
  </div>
</template>
