// packages/nextjs-app/app/components/DatasetTable.tsx
'use client';

import { FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PidComponent } from '@kit-data-manager/react-pid-component';
import { cn } from '@/lib/utils';
import { useCallback, useEffect, useRef, useState } from 'react';

export interface Dataset {
  id: string;
  title: string;
  doi: string;
  license: string;
}

interface DatasetTableProps {
  datasets: Dataset[];
  className?: string;
  darkMode?: boolean;
}

const columns = [
  { key: 'title', label: 'Title', initialWidth: 40 },
  { key: 'doi', label: 'DOI', initialWidth: 30 },
  { key: 'license', label: 'License', initialWidth: 20 },
  { key: 'actions', label: 'Actions', initialWidth: 10 },
];

export function DatasetTable({ datasets, className, darkMode = false }: DatasetTableProps) {
  const [columnWidths, setColumnWidths] = useState<Record<string, number>>(() =>
    Object.fromEntries(columns.map((c) => [c.key, c.initialWidth])),
  );
  const resizingRef = useRef<{ key: string; startX: number; startWidth: number } | null>(null);
  const tableRef = useRef<HTMLTableElement>(null);

  const onMouseMove = useCallback((e: MouseEvent) => {
    const resizing = resizingRef.current;
    if (!resizing || !tableRef.current) return;
    const tableWidth = tableRef.current.offsetWidth;
    const deltaPercent = ((e.clientX - resizing.startX) / tableWidth) * 100;
    const newWidth = Math.max(5, resizing.startWidth + deltaPercent);
    setColumnWidths((prev) => ({ ...prev, [resizing.key]: newWidth }));
  }, []);

  const onMouseUp = useCallback(() => {
    resizingRef.current = null;
    document.removeEventListener('mousemove', onMouseMove);
    document.removeEventListener('mouseup', onMouseUp);
  }, [onMouseMove]);

  const onResizeStart = useCallback(
    (e: React.MouseEvent, key: string) => {
      e.preventDefault();
      resizingRef.current = { key, startX: e.clientX, startWidth: columnWidths[key] };
      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
    },
    [columnWidths, onMouseMove, onMouseUp],
  );

  useEffect(() => {
    return () => {
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };
  }, [onMouseMove, onMouseUp]);

  return (
    <div className={cn('rounded-xl border bg-card shadow overflow-hidden', className)}>
      <div className="flex items-center gap-3 p-6 border-b">
        <FileText className="h-5 w-5 text-muted-foreground" />
        <h2 className="text-lg font-semibold text-foreground">Lorem ipsum dolor</h2>
      </div>
      <div style={{ overflowX: 'auto' }}>
        <table ref={tableRef} className="w-full" style={{ tableLayout: 'fixed', width: '100%' }}>
          <thead>
          <tr className="border-b">
            {columns.map((col) => (
              <th
                key={col.key}
                className="text-left text-xs font-semibold uppercase tracking-wider px-6 py-3 relative select-none text-muted-foreground bg-card"
                style={{ width: `${columnWidths[col.key]}%` }}
              >
                {col.label}
                <span
                  onMouseDown={(e) => onResizeStart(e, col.key)}
                  className="absolute right-0 top-0 bottom-0 w-1 cursor-col-resize hover:bg-primary/20"
                />
              </th>
            ))}
          </tr>
          </thead>
          <tbody>
          {datasets.map((dataset) => (
            <tr key={dataset.id} className="border-b transition-colors hover:bg-muted/50">
              <td
                className="px-6 py-4 text-sm overflow-hidden text-ellipsis whitespace-nowrap text-foreground">{dataset.title}</td>
              <td className="px-6 py-4">
                <div className="overflow-hidden">
                  <PidComponent value={dataset.doi} emphasizeComponent={false} darkMode={darkMode ? 'dark' : 'light'}
                                width="100%" />
                </div>
              </td>
              <td className="px-6 py-4">
                <div className="overflow-hidden">
                  <PidComponent value={dataset.license} emphasizeComponent={false}
                                darkMode={darkMode ? 'dark' : 'light'} width="100%" />
                </div>
              </td>
              <td className="px-6 py-4 overflow-hidden">
                <Button variant="secondary" size="sm">
                  View
                </Button>
              </td>
            </tr>
          ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// packages/vue-library/demo/components/DatasetTable.vue
<script lang="ts" setup>
import { PidComponent } from '../../lib';
import { reactive } from 'vue';

interface Dataset {
  id: string;
  title: string;
  doi: string;
  license: string;
}

defineProps<{
  datasets: Dataset[];
  darkMode?: boolean;
}>();

const columnWidths = reactive<Record<string, number>>({
  title: 30,
  doi: 30,
  license: 25,
  actions: 15,
});

let resizing: { key: string; startX: number; startWidth: number } | null = null;

function onResizeStart(event: MouseEvent, key: string) {
  event.preventDefault();
  resizing = { key, startX: event.clientX, startWidth: columnWidths[key] };
  document.addEventListener('mousemove', onResizeMove);
  document.addEventListener('mouseup', onResizeEnd);
}

function onResizeMove(event: MouseEvent) {
  if (!resizing) return;
  const table = document.querySelector('.dataset-table-inner') as HTMLElement | null;
  if (!table) return;
  const tableWidth = table.offsetWidth;
  const deltaPercent = ((event.clientX - resizing.startX) / tableWidth) * 100;
  const newWidth = Math.max(5, resizing.startWidth + deltaPercent);
  columnWidths[resizing.key] = newWidth;
}

function onResizeEnd() {
  resizing = null;
  document.removeEventListener('mousemove', onResizeMove);
  document.removeEventListener('mouseup', onResizeEnd);
}
</script>

<template>
  <v-card :color="darkMode ? 'grey-darken-3' : 'white'" elevation="1" style="overflow: hidden">
    <v-card-title class="d-flex align-center pa-4 border-b" :class="darkMode ? 'text-white' : 'text-grey-darken-3'">
      <v-icon class="mr-2" :class="darkMode ? 'text-grey-lighten-1' : 'text-grey-darken-2'">mdi-file-document</v-icon>
      <span class="text-h6">Related Datasets</span>
    </v-card-title>
    <div style="overflow-x: auto">
      <v-table :color="darkMode ? 'grey-darken-3' : 'white'" class="dataset-table-inner elevation-0"
               style="table-layout: fixed; width: 100%">
        <thead>
        <tr>
          <th
            v-for="col in [
                { key: 'title', label: 'Title' },
                { key: 'doi', label: 'DOI' },
                { key: 'license', label: 'License' },
                { key: 'actions', label: 'Actions' },
              ]"
            :key="col.key"
            :style="{ width: columnWidths[col.key] + '%', position: 'relative', userSelect: 'none' }"
          >
            {{ col.label }}
            <span
              class="resize-handle"
              @mousedown.prevent="onResizeStart($event, col.key)"
            ></span>
          </th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="item in datasets" :key="item.id">
          <td :class="darkMode ? 'text-white' : 'text-grey-darken-3'"
              style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap">{{ item.title }}
          </td>
          <td style="overflow: hidden; min-width: 0;">
            <div style="min-height: 24px; max-height: 80px; overflow: hidden;">
              <pid-component :emphasize-component="false" :dark-mode="darkMode ? 'dark' : 'light'" :value="item.doi"
                             style="display: block;" width="100%" />
            </div>
          </td>
          <td style="overflow: hidden; min-width: 0;">
            <div style="min-height: 24px; max-height: 80px; overflow: hidden;">
              <pid-component :emphasize-component="false" :dark-mode="darkMode ? 'dark' : 'light'" :value="item.license"
                             style="display: block;" width="100%" />
            </div>
          </td>
          <td style="overflow: hidden">
            <v-btn color="primary" size="small" variant="text">View</v-btn>
          </td>
        </tr>
        </tbody>
      </v-table>
    </div>
  </v-card>
</template>

<style scoped>
.resize-handle {
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 4px;
  cursor: col-resize;
  background: transparent;
}

.resize-handle:hover {
  background: #90caf9;
}
</style>
