// packages/nextjs-app/app/components/DoiCard.tsx
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PidComponent } from '@kit-data-manager/react-pid-component';

interface DoiCardProps {
  value: string;
  license?: string;
  className?: string;
  darkMode?: boolean;
}

export function DoiCard({ value, license, className, darkMode = false }: DoiCardProps) {
  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          Digital Object Identifier
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="min-h-[120px] max-h-[300px] overflow-hidden">
          <PidComponent value={value} darkMode={darkMode ? 'dark' : 'light'} width="100%" />
        </div>
        {license && (
          <div className="mt-4 pt-4 border-t">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider mb-3 text-muted-foreground">
              License
            </CardTitle>
            <div className="min-h-[24px] max-h-[60px] overflow-hidden">
              <PidComponent value={license} darkMode={darkMode ? 'dark' : 'light'} width="100%" />
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// packages/vue-library/demo/components/DoiCard.vue
<script lang="ts" setup>
import { PidComponent } from '../../lib';

defineProps<{
  value: string;
  license?: string;
  darkMode?: boolean;
}>();
</script>

<template>
  <v-card :color="darkMode ? 'grey-darken-3' : 'white'" class="fill-height" elevation="1">
    <v-card-text>
      <div class="text-caption text-uppercase font-weight-bold mb-3"
           :class="darkMode ? 'text-grey-lighten-1' : 'text-grey-darken-2'">
        Digital Object Identifier
      </div>
      <div style="min-height: 120px; max-height: 300px; overflow: hidden;">
        <pid-component :value="value" :dark-mode="darkMode ? 'dark' : 'light'" style="display: block;" width="100%" />
      </div>
      <v-divider v-if="license" class="my-4"></v-divider>
      <template v-if="license">
        <div class="text-caption text-uppercase font-weight-bold mb-3"
             :class="darkMode ? 'text-grey-lighten-1' : 'text-grey-darken-2'">
          License
        </div>
        <div style="min-height: 80px; max-height: 200px; overflow: hidden;">
          <pid-component :value="license" :dark-mode="darkMode ? 'dark' : 'light'" style="display: block;"
                         width="100%" />
        </div>
      </template>
    </v-card-text>
  </v-card>
</template>
