// packages/angular-library/src/app/components/hero-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

@Component({
  selector: 'app-hero-card',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatChipsModule,
    MatButtonModule,
    MatIconModule,
    MatDividerModule,
    PidComponent,
  ],
  template: `
    <mat-card [class]="darkMode ? 'bg-gray-800' : 'bg-white'" class="hero-card">
      <mat-card-header>
        <mat-chip-set>
          <mat-chip color="primary" highlighted>DOI</mat-chip>
          <mat-chip color="accent" highlighted>Research Data</mat-chip>
        </mat-chip-set>
      </mat-card-header>
      <mat-card-content>
        <h1 [class]="darkMode ? 'text-white' : 'text-gray-900'" class="hero-title">{{ title }}</h1>
        <p [class]="darkMode ? 'text-gray-300' : 'text-gray-600'" class="hero-description">{{ description }}</p>
      </mat-card-content>
      <mat-card-actions>
        <button mat-flat-button color="primary">
          <mat-icon>download</mat-icon>
          Download Dataset
        </button>
        <button mat-stroked-button [color]="darkMode ? 'accent' : 'primary'">
          <mat-icon>open_in_new</mat-icon>
          View Source
        </button>
      </mat-card-actions>
    </mat-card>
  `,
  styles: [`
    .hero-card {
      padding: 24px;
    }

    .hero-title {
      font-size: 24px;
      font-weight: 700;
      margin: 16px 0;
      line-height: 1.3;
    }

    .hero-description {
      font-size: 14px;
      line-height: 1.6;
      margin-bottom: 24px;
    }

    mat-card-actions {
      display: flex;
      gap: 12px;
    }
  `],
})
export class HeroCardComponent {
  @Input() title = '';
  @Input() description = '';
  @Input() darkMode = false;
}

// packages/vue-library/demo/components/HeroCard.vue
<script lang="ts" setup>

defineProps<{
  title?: string;
  description?: string;
  doi?: string;
  darkMode?: boolean;
}>();
</script>

<template>
  <v-card :color="darkMode ? 'grey-darken-3' : 'white'" class="fill-height" elevation="1">
    <v-card-item>
      <template #prepend>
        <div class="d-flex gap-2">
          <v-chip size="small" :color="darkMode ? 'blue-darken-3' : 'blue-lighten-5'"
                  :text-color="darkMode ? 'blue-lighten-2' : 'blue-darken-2'">DOI
          </v-chip>
          <v-chip size="small" :color="darkMode ? 'green-darken-3' : 'green-lighten-5'"
                  :text-color="darkMode ? 'green-lighten-2' : 'green-darken-2'">Research Data
          </v-chip>
        </div>
      </template>
    </v-card-item>
    <v-card-text>
      <h1 class="text-h5 font-weight-bold mb-2" :class="darkMode ? 'text-white' : 'text-grey-darken-3'">
        {{ title || 'This is an example webpage' }}
      </h1>
      <p class="text-body-2 mb-6" :class="darkMode ? 'text-grey-lighten-1' : 'text-grey-darken-2'">
        {{ description || 'This is an example of how the pid-component can be used within a Next.js app. Demo showcases DOIs (e.g. 10.5281/zenodo.13629109), ORCIDs (e.g. 0009-0005-2800-4833), RORs (e.g. https://ror.org/04t3en479), SPDX licenses (e.g. Apache-2.0), and more.'
        }}
      </p>
    </v-card-text>
    <v-card-actions>
      <v-btn color="primary" prepend-icon="mdi-download">Download Dataset</v-btn>
      <v-btn :color="darkMode ? 'white' : 'primary'" prepend-icon="mdi-open-in-new" variant="outlined">View Source
      </v-btn>
    </v-card-actions>
  </v-card>
</template>
