// packages/angular-library/src/app/components/author-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { PidComponent } from '@kit-data-manager/angular-pid-component';

export interface Author {
  orcid: string;
  name: string;
  institution?: string;
}

@Component({
  selector: 'app-author-card',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    PidComponent,
  ],
  template: `
    <mat-card class="author-card">
      <div class="author-content">
        <div class="avatar-placeholder">
          {{ getInitials(author.name) }}
        </div>
        <div class="author-info">
          <h3 class="author-name">{{ author.name }}</h3>
          @if (author.institution) {
            <p class="author-institution">{{ author.institution }}</p>
          }
          <div style="min-height: 24px; max-height: 80px; overflow: hidden;">
            <pid-component [value]="author.orcid" [emphasizeComponent]="false" width="100%" />
          </div>
        </div>
      </div>
    </mat-card>
  `,
  styles: [`
    .author-card {
      padding: 20px;
      overflow: hidden;
    }

    .author-content {
      display: flex;
      gap: 16px;
      align-items: flex-start;
    }

    .avatar-placeholder {
      width: 48px;
      height: 48px;
      border-radius: 50%;
      background: #e8eaf6;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 16px;
      font-weight: 600;
      color: #3f51b5;
      flex-shrink: 0;
    }

    .author-info {
      flex: 1;
      min-width: 0;
    }

    .author-name {
      font-size: 16px;
      font-weight: 600;
      color: #212121;
      margin: 0 0 4px 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .author-role {
      font-size: 13px;
      color: #9e9e9e;
      margin: 0 0 4px 0;
    }

    .author-institution {
      font-size: 12px;
      color: #bdbdbd;
      margin: 0 0 12px 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
  `],
})
export class AuthorCardComponent {
  @Input() author!: Author;

  getInitials(name: string): string {
    return name.split(' ').map(n => n[0]).join('');
  }
}

@Component({
  selector: 'app-author-grid',
  standalone: true,
  imports: [CommonModule, AuthorCardComponent],
  template: `
    <div class="author-grid">
      <h2 class="grid-title">Developers of the pid-component</h2>
      <div class="grid">
        @for (author of authors; track author.orcid) {
          <app-author-card [author]="author" />
        }
      </div>
    </div>
  `,
  styles: [`
    .author-grid {
      margin-bottom: 32px;
    }

    .grid-title {
      font-size: 18px;
      font-weight: 600;
      color: #212121;
      margin-bottom: 16px;
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 16px;
    }
  `],
})
export class AuthorGridComponent {
  @Input() authors: Author[] = [];
}

// packages/nextjs-app/app/demo/components/AuthorCard.tsx
'use client';

import * as Avatar from '@radix-ui/react-avatar';
import { PidComponent } from '@kit-data-manager/react-pid-component';
import { cn } from '../lib/utils';

interface Author {
  orcid: string;
  name: string;
  institution?: string;
}

interface AuthorCardProps {
  author: Author;
  className?: string;
}

export function AuthorCard({ author, className }: AuthorCardProps) {
  const initials = author.name.split(' ').map(n => n[0]).join('');

  return (
    <div className={cn('rounded-xl border border-slate-200 bg-white p-5 shadow-sm', className)}>
      <div className="flex items-start gap-4">
        <Avatar.Root
          className="inline-flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-full border border-slate-200">
          <Avatar.Image src={`https://api.dicebear.com/7.x/initials/svg?seed=${author.name}`} alt={author.name} />
          <Avatar.Fallback
            className="flex h-full w-full items-center justify-center bg-slate-100 text-sm font-medium text-slate-600">
            {initials}
          </Avatar.Fallback>
        </Avatar.Root>
        <div className="flex-1 min-w-0">
          <h3 className="text-sm font-semibold text-slate-900 truncate">{author.name}</h3>
          {author.institution && (
            <p className="text-xs text-slate-400 mt-1">{author.institution}</p>
          )}
          <div className="mt-3 relative overflow-hidden">
            <PidComponent value={author.orcid} emphasizeComponent={false} width="100%" />
          </div>
        </div>
      </div>
    </div>
  );
}

export function AuthorGrid({ authors, className }: { authors: Author[]; className?: string }) {
  return (
    <div className={cn('mb-8', className)}>
      <h2 className="text-lg font-semibold text-slate-900 flex items-center gap-2 mb-4">
        Developers of the pid-component
      </h2>
      <div className="grid grid-cols-3 gap-4">
        {authors.map((author) => (
          <AuthorCard key={author.orcid} author={author} />
        ))}
      </div>
    </div>
  );
}
